---
# tasks file for skillthoughts
- name: remove existing container if this exists
  raw: docker rm -f {{envname}}
  ignore_errors: true

- name: remove unsed docker resources
  raw: docker system prune -af

- name: deploy application to thet target system
  raw: docker run -d --name {{envname}} -p {{port}}:8080 skillthoughts/tomcat:{{appversion}} 
