---
# tasks file for skillthoughts
- name: remove existing container if this exists
  raw: docker rm -f st
  ignore_errors: true

- name: deploy application to thet target system
  raw: docker run -dti --name st -p 80:8080 skillthoughts/tomcat:2.0 /bin/bash

- name: start tomcat server
  command: ./startup.sh
  args:
    chdir: /opt/tomcat/bin
